# Generated by Django 4.2.14 on 2024-08-04 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="title",
            field=models.CharField(default="tops", max_length=100),
        ),
    ]
