# Generated by Django 4.2.14 on 2024-08-04 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_category_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="url",
            field=models.URLField(default="1234"),
        ),
        migrations.AlterField(
            model_name="category",
            name="title",
            field=models.CharField(max_length=100),
        ),
    ]
