# Generated by Django 4.2.14 on 2024-09-04 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_colorimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="shipping_size",
            field=models.CharField(
                choices=[
                    ("normal", "ノーマル"),
                    ("large", "大"),
                    ("extra_large", "特大"),
                ],
                default="normal",
                max_length=20,
            ),
        ),
    ]
