# Generated by Django 4.2.14 on 2024-08-13 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0002_cart_total_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="total_price",
        ),
    ]
