# Generated by Django 4.2.14 on 2024-09-02 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0005_remove_cart_total_price_alter_cartitem_cart"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="color",
            field=models.CharField(default="black", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cartitem",
            name="size",
            field=models.CharField(default="s", max_length=50),
            preserve_default=False,
        ),
    ]
